name: Test

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '22.12.x'
        os:
          - macos-latest
          # TODO(dsanders11: Enable these once we fix tests on those platforms in CI
          # - ubuntu-latest
          # - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "${{ matrix.node-version }}"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
